class ArrayInterface:
    def find(self, search_value):
        ...

    def insert(self, value):
        ...
    
    def delete(self, value):
        ...
    
    def display(self):
        ...

    def get_min(self):
        ...

    def get_max(self):
        ...

    def quick_sort(self):
        ...

    def partition(self, pivot):
        ...